### ISSUE TITLE
The evaluation result

### ISSUE THREAD

**Issue by mqchen0916** [forever1260/HandFold#1]
Thanks for the contribution. Besides, I wonder how to convert the evaluation result to a .txt file to check the estimation results in detail.

**Comment by cwc1260** [comment]
Thanks for your interest in our work. You can use the camera parameter to transform 3D joint coordinates into the 2D uvd format for evaluation. For instance, in ICVL dataset, you can use the following code to process the transformation:
`estimation = torch.matmul((estimation.view(-1,JOINT_NUM,3) + offset.view(-1,1,3))* volume_length.view(-1,1,1), rotate.view(-1,3,3).transpose(1,2)) `
`uvd[:,:,0] = estimation[:,:,0] * 241.42 / estimation[:,:,2] + 160.`
`uvd[:,:,1] = 120. - estimation[:,:,1] * 241.42 / estimation[:,:,2] `
`uvd[:,:,2] = estimation[:,:,2]` 
where the 160, 120 represent the half of the image width, height, and 241.42 is the focal length. Note that, offset, volume_length and rotate are all provided by the preprocessed dataset.
