### ISSUE TITLE
Can't reimplement real-time inference at about 84FPS

### ISSUE THREAD

**Issue by MiYanDoris** [forever1260/HandFold#2]
Thanks for your interesting work! When we run this code, we meet with some problems about code efficiency. In detail, we find that it takes about 70ms for a single forward on a V100 GPU, which is inconsistent with 3.7ms in your paper. We are not sure whether it is due to our misuse of your code or the difference between devices. 
By the way, we append our testing code here for your reference.

```
netR = PointNet_Plus(opt).cuda()

with torch.no_grad():
    for i in range(20):
        t0 = time.time()

        points = torch.randn((1, 1024, 6)).cuda()
        inputs_level1, inputs_level1_center = group_points(points, opt)
        inputs_level1, inputs_level1_center = Variable(inputs_level1, requires_grad=False), Variable(inputs_level1_center, requires_grad=False)

        t1 = time.time()
        fold1, fold2, estimation = netR(inputs_level1, inputs_level1_center)
        t2 = time.time()
        print(t1 - t0)
        print(t2 - t1)

```

Really nice work, thanks!

**Comment by cwc1260** [comment]
Thank you for your interest about our work.  70ms is really weird.  We recommend you to apply ‘torch.jit.trace’ to accelerate the inference.
